name: CI
on:
  pull_request:
    branches:
      - develop
    paths: # Recuado para ficar dentro de pull_request
      - "src/**"
      - "tests/**"
      - "package.json"
      - "package-lock.json"

env: # O termo correto é 'env', sem o ponto na frente
  PORT: ${{ vars.PORT }}
  API_TOKEN: ${{ secrets.API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Instalar Node
        uses: actions/setup-node@v4 # Atualizado para v4
        with:
          node-version: "22"

      - name: Instalar dependencias
        run: npm install

      - name: Roda tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Instalar dependencias
        run: npm install

      - name: build
        run: npm run build
